name: Notify Slack Action
description: Send Github Actions workflow status notifications to Slack
author: RavSam Web Solutions
inputs:
  status:
    description: Job Status
    required: true
  token:
    description: Github Token for accessing workflow url
    required: false
    default: ""
  notification_title:
    description: Specify on the notification message title
    required: false
    default: "New Github Action Run"
  message_format:
    description: Specify on the notification message format
    required: false
    default: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>"
  footer:
    description: Specify the footer of the message
    required: false
    default: "<{run_url}|View Run> | Developed by <https://www.ravsam.in|RavSam>"
  notify_when:
    description: Specify on which events a slack notification is sent
    required: false
    default: "success,failure,cancelled,warnings,skipped"
  mention_users:
    description: Specify the slack IDs of users you want to mention
    required: false
    default: ""
  mention_users_when:
    description: Specify on which events you want to mention the users
    required: false
    default: "success,failure,cancelled,warnings,skipped"
  mention_groups:
    description: Specify the slack IDs of groups you want to mention
    required: false
    default: ""
  mention_groups_when:
    description: Specify on which events you want to mention the groups
    required: false
    default: "success,failure,cancelled,warnings,skipped"
  icon_success:
    description: Specify on icon to be used when event is success
    required: false
    default: ":heavy_check_mark:"
  icon_failure:
    description: Specify on icon to be used when event is failure
    required: false
    default: ":x:"
  icon_cancelled:
    description: Specify on icon to be used when event is cancelled
    required: false
    default: ":x:"
  icon_warnings:
    description: Specify on icon to be used when event is warnings
    required: false
    default: ":large_orange_diamond:"
  icon_skipped:
    description: Specify on icon to be used when event is skipped
    required: false
    default: ":fast_forward:"

branding:
  icon: send
  color: blue

runs:
  using: "node16"
  main: "dist/index.js"
